"""baseline

Revision ID: c6c4ebf10225
Revises: 
Create Date: 2026-09-05 13:37:43.438108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c4ebf10225'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kurs_id', sa.String(length=100), nullable=False),
    sa.Column('grading_params', sa.JSON(), nullable=True),
    sa.Column('grade_thresholds', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_kurs_id'), ['kurs_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('klass_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['klass_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('klass_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('facit_mode', sa.String(length=32), nullable=False),
    sa.Column('custom_params', sa.Text(), nullable=True),
    sa.Column('questions', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # SCHEMA DRIFT (documented decision): `facit` exists in the real wiseos.db
    # but is NOT declared in the Test model. Included here (Option A) so fresh
    # databases match the real DB. A future autogenerate will detect this
    # drift and propose dropping it — that is intentional.
    sa.Column('facit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['klass_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('grade_level', sa.String(length=50), nullable=True),
    sa.Column('problem_text', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grading_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('identification_method', sa.String(length=32), nullable=False),
    sa.Column('identification_confidence', sa.Float(), nullable=False),
    # NULLABLE DRIFT (documented decision): `scan_pages` allows NULL in the real
    # wiseos.db (it was added via ALTER TABLE, which cannot set NOT NULL).
    # The baseline uses the model's stricter NOT NULL for fresh databases;
    # the existing DB keeps its nullable state via stamping — no ALTER is run
    # to force existing rows/columns to comply.
    sa.Column('scan_pages', sa.JSON(), nullable=False),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('anonymized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grading_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grading_results_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grading_results_test_id'), ['test_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assignment_id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('student_pseudonym', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('wolfram_verification', sa.JSON(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('wolfram_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_overall', sa.Float(), nullable=True),
    # NULLABLE DRIFT (documented decision): `requires_review` and
    # `review_status` allow NULL in the real wiseos.db (added via ALTER TABLE).
    # The baseline uses the model's stricter NOT NULL for fresh databases;
    # the existing DB keeps its nullable state via stamping.
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('final_feedback', sa.Text(), nullable=True),
    sa.Column('final_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_student_pseudonym'), ['student_pseudonym'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_student_pseudonym'))

    op.drop_table('submissions')
    with op.batch_alter_table('grading_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grading_results_test_id'))
        batch_op.drop_index(batch_op.f('ix_grading_results_student_id'))

    op.drop_table('grading_results')
    op.drop_table('assignments')
    op.drop_table('answer_keys')
    op.drop_table('tests')
    op.drop_table('teachers')
    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_classes_kurs_id'))

    op.drop_table('classes')
    # ### end Alembic commands ###
